### ISSUE TITLE
LICENSE not in pypi tarball

### ISSUE THREAD

**Issue by dvzrv** [alex-rudakov/sphinx-argparse#116]
Hi!

I'm currently en route to moving sphinx-argparse to the official repositories of Arch Linux.
As this software is MIT licensed I'm required to package the license file alongside the software.
However, when downloading the pypi source tarball, the LICENSE file is missing.
It would be great, if this could be added, as not only distributions require clear license statements, but also e.g. companies, that try to incorporate the software in some local build chain.

Thanks a lot!

**Comment by kyluca** [comment]
I believe this PR should be sufficient to get the LICENSE file into the source dist https://github.com/ribozz/sphinx-argparse/pull/118

I couldn't see where the tar release was built during any Travis/build scripts, assuming it's done manually with `python setup.py sdist` and uploaded separately? Would be good to add the commands to the `.travis.yml`.

**Comment by dvzrv** [comment]
This repo is not the current upstream anymore, so closing.
