### ISSUE TITLE
Help with maintainance

### ISSUE THREAD

**Issue by gaborbernat** [alex-rudakov/sphinx-argparse#134]
There are a few PRs and issues open and unaddressed. Do you need help with maintaining this project? I can offer to chip in (I'm the maintainer of the virtualenv/tox tools FYI).

**Comment by mondeja** [comment]
It seems that the owner is completely dissapeared, do you want to start a fork of this package? I will help you maintaining it.

**Comment by gaborbernat** [comment]
In the end made my own https://tox.readthedocs.io/en/rewrite/cli_interface.html#-root implementation optimized for sub commands, I'll probably release it separately at some point.

**Comment by gaborbernat** [comment]
Done now under https://pypi.org/project/sphinx-argparse-cli

**Comment by mondeja** [comment]
Thank you! :+1:
